### ISSUE TITLE
[Request] When using FileSystemAccess API, save the file handle in IndexedDB

### ISSUE THREAD

**Issue by Nu11u5** [minht11/local-music-pwa#24]
IndexedDB can serialize and store file handles from the FileSystemAccess API.  This would allow the app to prompt the user to approve access to a folder that was previously selected, instead of having to re-add the folder using the file picker.

https://web.dev/file-system-access/#storing-file-handles-or-directory-handles-in-indexeddb

**Comment by minht11** [comment]
The app has the persistence functionality, but previous upgrade of an UI framework changed some behaviours of object tracking. It should be fixed now.
