### ISSUE TITLE
Playlist becomes Album after Restarting

### ISSUE THREAD

**Issue by albumcovers** [minht11/local-music-pwa#35]
I restarted my PC and then all the sudden my playlist got converted into an album. The playlist is still there it's just empty. All my songs are in a new album and in that album there album metadata is corrupted by saying they are in a "<unknown>" album.

**Comment by minht11** [comment]
I could reproduce issue with tracks added to playlist not persisting, could not really reproduce playlist becoming album part. Could you give more precise reproduction if the issue still persists?
